"""
Centralized configuration for Claudius.
"""
import os

CLAUDIUS_DIR = "/opt/claudius"
CLAUDE_MD = CLAUDIUS_DIR + "/CLAUDE.md"
MEMORY_MD = CLAUDIUS_DIR + "/MEMORY.md"
LOG_FILE = "/var/log/claudius-api.log"

CRON_SECRET = os.environ.get("CRON_SECRET")
ADMIN_SECRET = os.environ.get("ADMIN_SECRET")
TELEGRAM_BOT_TOKEN = os.environ.get("TELEGRAM_BOT_TOKEN")
OWNER_CHAT_ID = 7070679785
OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY")
FAL_KEY = os.environ.get("FAL_KEY")
SUPABASE_URL = os.environ.get("NEXT_PUBLIC_SUPABASE_URL")
SUPABASE_ANON_KEY = os.environ.get("NEXT_PUBLIC_SUPABASE_ANON_KEY")
ENGRAM_API_URL = os.environ.get("ENGRAM_API_URL", "http://localhost:3201/engram")

MAX_CONCURRENT_CLAUDE_SESSIONS = 2
DEFAULT_TIMEOUT = 600
QUEUE_TIMEOUT = 300
MEMORY_MAX_ENTRIES = 100
CONVERSATION_HISTORY_LIMIT = 20
CONVERSATION_TIMEOUT_HOURS = 24
MEMORY_RESTART_THRESHOLD_MB = 750
MEMORY_CHECK_INTERVAL = 30
MIN_AVAILABLE_MEMORY_MB = 500
MAX_CLAUDE_PROCESSES = 10
MAX_TOTAL_PROCESSES = 27
